apiVersion: apps/v1
kind: Deployment
metadata:
  name: digimon-fleet-manager-v2
  namespace: digimon
  labels:
    app: digimon-fleet-manager-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digimon-fleet-manager-v2
  template:
    metadata:
      labels:
        app: digimon-fleet-manager-v2
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: fleet-manager-v2
          image: ttl.sh/casey-digimon-fleet-v2:24h
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: data-storage
              mountPath: /data
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: fleet-data-v2-pvc
