apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-data-pvc
  namespace: digimon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
