apiVersion: v1
kind: Service
metadata:
  name: digimon-fleet-service
  namespace: digimon
spec:
  selector:
    app: digimon-fleet-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
